### PR TITLE
Add saveAvatar and CORS headers

### PR DESCRIPTION
**Pull request by reversefold**

### CODE REVIEW

**Comment by yelworc** [comment]
A few things I've noticed here:
* in `avatar_common/saveAvatarImages`, I think we could just move/rename the uploaded file instead of copying it by read+write
* unless I'm missing something, the `request` npm package is added but not used (apart from a commented-out call in `methods/avatar.js`)
* could use some cleanup before merging (tabs/spaces mix, commented out code, log statements; part of this is probably due to the jshint/jscs npm scripts not including new modules implicitly)

@Whizy has the final say on this as the API maintainer, he probably has more input.

**Comment by reversefold** [comment]
BTW, I'm copying the file instead of moving it as generally files uploaded via HTTP are temporary file which go away at the end of the request. I'm not 100% sure that our node HTTP API does this but I'd be surprised if it didn't. This can definitely be cleaned up, though, probably a copyFile method somewhere I missed when I was first writing this.

Good call on request, that was a path I went down that didn't pan out.

**Comment by reversefold** [comment]
jshint and jscs issues fixed in the avatar files (all of `methods/` directory shows as clean now).

**Comment by reversefold** [comment]
This PR is still open....

**Comment by Whizy** [comment]
Sorry it took so long to look at this! Could you create another PR for the new methods (I have already cherry picked some commits from here). I also think it would be best to remove avatar.saveSpritesheets/saveSingles in favour of god.avatar.saveSpritesheets/saveSingles for both client and server side generation (removing the need for avatar_common.js).

**Comment by reversefold** [comment]
@Whizy I'm not sure what you mean by creating a new PR. All this PR is is the addition of new methods and the node modules required for it to work (IIRC).

**Comment by reversefold** [comment]
As for using the god APIs I think the issue there was with authentication to the god APIs. I wasn't sure how we were going to authenticate the API calls from the spritesheet generator. Additionally, having the APIs available as both god and regular versions means that we can still support spritesheet generation on the client if needed.

**Comment by Whizy** [comment]
Closing this as https://github.com/ElevenGiants/eleven-http-api/pull/25 has been merged.

**Pull request closed without merging**
